name: Build proceedings paper
on: [push]
jobs:
  build-paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: LaTeX build
        uses: xu-cheng/latex-action@master
        with:
          working_directory: paper
          root_file: paper.tex
      - uses: actions/upload-artifact@v1
        with:
          name: paper.pdf
          path: paper/paper.pdf

